# Generated by Django 4.0.3 on 2022-03-20 11:31

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('owner_affilaite_program_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='items.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price_range_from', models.DateTimeField(blank=True, null=True)),
                ('original_price_range_to', models.DateTimeField(blank=True, null=True)),
                ('price_range_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_range_to', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reviews_score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('count_of_reviews', models.IntegerField(blank=True, null=True)),
                ('img_source_link', models.URLField(blank=True, null=True)),
                ('link_to_item', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('popular_ind', models.BooleanField(default=False)),
                ('recent_customer_name', models.CharField(blank=True, max_length=50, null=True)),
                ('recent_customer_desc', models.TextField(blank=True, null=True)),
                ('recent_customer_score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('benefits', models.ManyToManyField(to='items.benefits')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.category')),
                ('ownner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.owners')),
            ],
        ),
    ]
