# Generated by Django 4.0.3 on 2022-03-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="benefits",
            name="location",
        ),
        migrations.RemoveField(
            model_name="benefits",
            name="owner_affilaite_program_id",
        ),
        migrations.RemoveField(
            model_name="benefits",
            name="url",
        ),
        migrations.RemoveField(
            model_name="owners",
            name="description",
        ),
        migrations.AddField(
            model_name="benefits",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="owners",
            name="location",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="owners",
            name="owner_affilaite_program_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="owners",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
