# Generated by Django 4.0.3 on 2022-03-28 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_benefits_options_alter_items_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='original_price_range_from',
            new_name='original_price_from',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='original_price_range_to',
            new_name='original_price_to',
        ),
    ]
