# Generated by Django 4.0.3 on 2022-03-29 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_rename_original_price_range_from_items_original_price_from_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='ownner',
            new_name='owner',
        ),
    ]
