# Generated by Django 4.0.3 on 2022-03-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_rename_ownner_items_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='price',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
