# Generated by Django 4.0.3 on 2022-06-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_items_recent_customer_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='category',
            field=models.ManyToManyField(blank=True, to='items.category'),
        ),
        migrations.AlterField(
            model_name='items',
            name='description',
            field=models.TextField(blank=True, max_length=133, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='popular_ind',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='recent_customer_desc',
            field=models.TextField(blank=True, max_length=133, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='recent_customer_title',
            field=models.CharField(blank=True, max_length=133, null=True),
        ),
    ]
