# Generated by Django 4.0.3 on 2022-06-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_alter_items_category_alter_items_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='recent_customer_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='recent_customer_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
